# Generated by Django 5.1.15 on 2026-03-18 01:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('walk_mode', models.CharField(choices=[('group', 'Group Walk'), ('security', 'Security Escort'), ('friend', 'Walk With Friend')], max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text="e.g. 'Walk to Brunei', 'Library → Ayeduase'", max_length=150)),
                ('max_members', models.PositiveSmallIntegerField(default=6, help_text='Maximum group size')),
                ('origin_name', models.CharField(blank=True, default='', max_length=150)),
                ('origin_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('origin_lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('destination_name', models.CharField(max_length=150)),
                ('destination_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('destination_lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('status', models.CharField(choices=[('pending', 'Pending (waiting for members)'), ('active', 'Active (walking)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('monitored_by_security', models.BooleanField(default=False, help_text='Whether security is monitoring this walk')),
                ('arrived_safely', models.BooleanField(default=False)),
                ('departure_time', models.DateTimeField(blank=True, help_text='Planned departure time for group walks', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_walks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walk_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkSessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_role', models.CharField(choices=[('creator', 'Creator'), ('member', 'Member'), ('security_monitor', 'Security Monitor')], default='member', max_length=30)),
                ('participant_status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('declined', 'Declined'), ('left', 'Left')], default='joined', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_participations', to=settings.AUTH_USER_MODEL)),
                ('walk_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='walks.walksession')),
            ],
            options={
                'db_table': 'walk_session_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='walksession',
            index=models.Index(fields=['status', '-created_at'], name='idx_walk_status_time'),
        ),
        migrations.AddIndex(
            model_name='walksession',
            index=models.Index(fields=['created_by', '-created_at'], name='idx_walk_creator_time'),
        ),
        migrations.AddConstraint(
            model_name='walksessionparticipant',
            constraint=models.UniqueConstraint(fields=('walk_session', 'user'), name='uq_walk_participant'),
        ),
    ]
