# Generated by Django 5.1.15 on 2026-03-18 03:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('lighting', 'Broken/Missing Lighting'), ('infrastructure', 'Infrastructure Damage'), ('suspicious', 'Suspicious Activity'), ('unsafe_area', 'Unsafe Area'), ('harassment', 'Harassment'), ('theft', 'Theft'), ('vandalism', 'Vandalism'), ('signage', 'Missing/Damaged Signage'), ('other', 'Other'), ('general', 'General')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_text', models.CharField(blank=True, default='', help_text="e.g. 'Near Tech Junction', 'Behind Engineering Block'", max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='report_photos/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes from security/admin')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Security officer or admin assigned to handle this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issue_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_text', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes only visible to admin/security')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.issuereport')),
            ],
            options={
                'db_table': 'report_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='issuereport',
            index=models.Index(fields=['status', '-created_at'], name='idx_report_status_time'),
        ),
        migrations.AddIndex(
            model_name='issuereport',
            index=models.Index(fields=['reported_by', '-created_at'], name='idx_report_user_time'),
        ),
        migrations.AddIndex(
            model_name='issuereport',
            index=models.Index(fields=['category'], name='idx_report_category'),
        ),
        migrations.AddIndex(
            model_name='issuereport',
            index=models.Index(fields=['priority'], name='idx_report_priority'),
        ),
    ]
