# Generated by Django 5.1.15 on 2026-03-18 00:59

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('location_type', models.CharField(choices=[('hostel', 'Hostel'), ('facility', 'Facility'), ('landmark', 'Landmark'), ('gate', 'Gate'), ('bus_stop', 'Bus Stop'), ('medical', 'Medical'), ('academic', 'Academic'), ('security_post', 'Security Post')], max_length=50)),
                ('area', models.CharField(blank=True, default='', help_text='e.g. Residential, Academic, Commercial', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('safety_rating', models.FloatField(default=3.0, help_text='Safety rating out of 5.0')),
                ('lighting', models.CharField(choices=[('Well lit', 'Well lit'), ('Moderately lit', 'Moderately lit'), ('Poorly lit', 'Poorly lit'), ('Unlit', 'Unlit')], default='Moderately lit', max_length=50)),
                ('security_presence', models.CharField(choices=[('Patrol available', 'Patrol available'), ('Security post nearby', 'Security post nearby'), ('Limited', 'Limited'), ('None', 'None')], default='Limited', max_length=50)),
                ('recent_activity', models.CharField(blank=True, default='Normal activity levels', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Show in popular/quick-access lists')),
            ],
            options={
                'db_table': 'campus_locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='idx_campus_loc_active'), models.Index(fields=['location_type'], name='idx_campus_loc_type'), models.Index(fields=['is_popular'], name='idx_campus_loc_popular')],
            },
        ),
    ]
