# Generated by Django 5.1.15 on 2026-03-18 01:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_code', models.CharField(blank=True, help_text='Auto-generated. Format: SOS-YYYYMMDD-XXXXXX', max_length=40, unique=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_method', models.CharField(choices=[('button', 'SOS Button'), ('shake', 'Phone Shake'), ('voice', 'Voice Command'), ('auto', 'Automatic')], default='button', max_length=30)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('location_text', models.CharField(blank=True, default='', help_text="Human-readable location, e.g. 'Near Brunei Hostel'", max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes from student or security')),
                ('cancelled_by_user', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_contact_notified', models.BooleanField(default=False)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sos_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sos_alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSAlertEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('triggered', 'SOS Triggered'), ('status_changed', 'Status Changed'), ('patrol_assigned', 'Patrol Assigned'), ('patrol_accepted', 'Patrol Accepted'), ('patrol_arrived', 'Patrol Arrived'), ('note_added', 'Note Added'), ('contact_notified', 'Emergency Contact Notified'), ('cancelled', 'Cancelled'), ('resolved', 'Resolved'), ('location_updated', 'Location Updated')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Extra context about the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, help_text='Who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_actions', to=settings.AUTH_USER_MODEL)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sos.sosalert')),
            ],
            options={
                'db_table': 'sos_alert_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['status', '-triggered_at'], name='idx_sos_status_time'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['user', '-triggered_at'], name='idx_sos_user_time'),
        ),
        migrations.AddIndex(
            model_name='sosalertevent',
            index=models.Index(fields=['sos_alert', '-created_at'], name='idx_sos_events_alert_time'),
        ),
    ]
