# Generated by Django 5.1.15 on 2026-03-18 01:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('responding', 'Responding'), ('on_break', 'On Break'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('current_lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('current_lng', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('area_of_patrol', models.CharField(blank=True, default='', help_text='e.g. Main Campus, Brunei Area, Ayeduase', max_length=150)),
            ],
            options={
                'db_table': 'patrol_units',
                'ordering': ['unit_name'],
                'indexes': [models.Index(fields=['status'], name='idx_patrol_status')],
            },
        ),
        migrations.CreateModel(
            name='PatrolUnitMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_lead', models.BooleanField(default=False, help_text='Unit lead / team leader')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('patrol_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='patrols.patrolunit')),
                ('security_user', models.OneToOneField(limit_choices_to={'user_role': 'security'}, on_delete=django.db.models.deletion.CASCADE, related_name='patrol_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patrol_unit_members',
                'constraints': [models.UniqueConstraint(fields=('patrol_unit', 'security_user'), name='uq_patrol_unit_member')],
            },
        ),
        migrations.CreateModel(
            name='SOSAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('en_route_at', models.DateTimeField(blank=True, null=True)),
                ('on_scene_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('patrol_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='patrols.patrolunit')),
                ('security_user', models.ForeignKey(blank=True, help_text='Individual officer (if no patrol unit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_assignments', to=settings.AUTH_USER_MODEL)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sos.sosalert')),
            ],
            options={
                'db_table': 'sos_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['sos_alert', 'status'], name='idx_assignment_alert_status'), models.Index(fields=['patrol_unit', 'status'], name='idx_assignment_patrol_status'), models.Index(fields=['security_user', 'status'], name='idx_assignment_security_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('patrol_unit__isnull', False), ('security_user__isnull', False), _connector='OR'), name='chk_assignment_has_responder')],
            },
        ),
    ]
