# Generated by Django 5.1.15 on 2026-03-18 01:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLiveLocation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='live_location', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True)),
                ('speed_mps', models.FloatField(blank=True, help_text='Speed in meters per second', null=True)),
                ('source', models.CharField(choices=[('gps', 'GPS'), ('network', 'Network'), ('fused', 'Fused'), ('manual', 'Manual')], default='gps', max_length=20)),
                ('is_sharing', models.BooleanField(default=False, help_text='True when user has an active walk, SOS, or share session')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_live_locations',
                'indexes': [models.Index(fields=['-updated_at'], name='idx_live_loc_updated')],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('general', 'General'), ('walk', 'Walk Session'), ('sos', 'SOS Alert'), ('share', 'Location Share')], default='general', max_length=20)),
                ('reference_id', models.UUIDField(blank=True, help_text='ID of the walk session, SOS alert, or share session', null=True)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('speed_mps', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_history',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='idx_loc_hist_user_time'), models.Index(fields=['context', 'reference_id', '-recorded_at'], name='idx_loc_hist_ctx_ref_time')],
            },
        ),
    ]
