# Generated by Django 5.1.15 on 2026-03-18 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('sos_alerts_enabled', models.BooleanField(default=True)),
                ('walk_updates_enabled', models.BooleanField(default=True)),
                ('chat_notifications_enabled', models.BooleanField(default=True)),
                ('share_location_enabled', models.BooleanField(default=True)),
                ('sound_alerts_enabled', models.BooleanField(default=True)),
                ('dark_mode_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='BroadcastAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('notice', 'Safety Notice'), ('shuttle', 'Shuttle Update'), ('security', 'Security Advisory'), ('emergency', 'Emergency'), ('maintenance', 'Maintenance'), ('general', 'General')], default='notice', max_length=20)),
                ('location', models.CharField(blank=True, default='', help_text="Related location (e.g. 'Tech Junction')", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Alert auto-hides after this time', null=True)),
                ('audience', models.CharField(default='all', help_text="'all', 'student', or 'security'", max_length=20)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'broadcast_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='idx_broadcast_active_time'), models.Index(fields=['alert_type'], name='idx_broadcast_type')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('sos', 'SOS Alert'), ('chat', 'Chat Message'), ('walk', 'Walk Update'), ('share', 'Location Share'), ('approval', 'Account Approval'), ('system', 'System'), ('security', 'Security Notice')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra payload (IDs, links, action data)')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via_push', models.BooleanField(default=False)),
                ('sent_via_ws', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='idx_notif_user_read_time'), models.Index(fields=['user', 'notification_type'], name='idx_notif_user_type')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_token', models.TextField(unique=True)),
                ('push_provider', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('web_push', 'Web Push')], default='fcm', max_length=30)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_devices',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_device_user_active')],
            },
        ),
    ]
